// Code generated by "stringer -type=SearcherName"; DO NOT EDIT.

package zapshit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Err-0]
	_ = x[InterceptWord-1]
	_ = x[Greeting-2]
	_ = x[TabledKnowledge-3]
	_ = x[Knowledge-4]
	_ = x[ChatGPT-5]
	_ = x[Helplook-6]
}

const _SearcherName_name = "ErrInterceptWordGreetingTabledKnowledgeKnowledgeChatGPTHelplook"

var _SearcherName_index = [...]uint8{0, 3, 16, 24, 39, 48, 55, 63}

func (i SearcherName) String() string {
	if i < 0 || i >= SearcherName(len(_SearcherName_index)-1) {
		return "SearcherName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SearcherName_name[_SearcherName_index[i]:_SearcherName_index[i+1]]
}
